//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ICSharpCode.UsageDataCollector.DataAccess.Collector
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class UDCContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new UDCContext object using the connection string found in the 'UDCContext' section of the application configuration file.
        /// </summary>
        public UDCContext() : base("name=UDCContext", "UDCContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new UDCContext object.
        /// </summary>
        public UDCContext(string connectionString) : base(connectionString, "UDCContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new UDCContext object.
        /// </summary>
        public UDCContext(EntityConnection connection) : base(connection, "UDCContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EnvironmentDataName> EnvironmentDataNames
        {
            get
            {
                if ((_EnvironmentDataNames == null))
                {
                    _EnvironmentDataNames = base.CreateObjectSet<EnvironmentDataName>("EnvironmentDataNames");
                }
                return _EnvironmentDataNames;
            }
        }
        private ObjectSet<EnvironmentDataName> _EnvironmentDataNames;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Feature> Features
        {
            get
            {
                if ((_Features == null))
                {
                    _Features = base.CreateObjectSet<Feature>("Features");
                }
                return _Features;
            }
        }
        private ObjectSet<Feature> _Features;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FeatureUse> FeatureUses
        {
            get
            {
                if ((_FeatureUses == null))
                {
                    _FeatureUses = base.CreateObjectSet<FeatureUse>("FeatureUses");
                }
                return _FeatureUses;
            }
        }
        private ObjectSet<FeatureUse> _FeatureUses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ExceptionGroup> ExceptionGroups
        {
            get
            {
                if ((_ExceptionGroups == null))
                {
                    _ExceptionGroups = base.CreateObjectSet<ExceptionGroup>("ExceptionGroups");
                }
                return _ExceptionGroups;
            }
        }
        private ObjectSet<ExceptionGroup> _ExceptionGroups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Exception> Exceptions
        {
            get
            {
                if ((_Exceptions == null))
                {
                    _Exceptions = base.CreateObjectSet<Exception>("Exceptions");
                }
                return _Exceptions;
            }
        }
        private ObjectSet<Exception> _Exceptions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ActivationMethod> ActivationMethods
        {
            get
            {
                if ((_ActivationMethods == null))
                {
                    _ActivationMethods = base.CreateObjectSet<ActivationMethod>("ActivationMethods");
                }
                return _ActivationMethods;
            }
        }
        private ObjectSet<ActivationMethod> _ActivationMethods;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EnvironmentData> EnvironmentDatas
        {
            get
            {
                if ((_EnvironmentDatas == null))
                {
                    _EnvironmentDatas = base.CreateObjectSet<EnvironmentData>("EnvironmentDatas");
                }
                return _EnvironmentDatas;
            }
        }
        private ObjectSet<EnvironmentData> _EnvironmentDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EnvironmentDataValue> EnvironmentDataValues
        {
            get
            {
                if ((_EnvironmentDataValues == null))
                {
                    _EnvironmentDataValues = base.CreateObjectSet<EnvironmentDataValue>("EnvironmentDataValues");
                }
                return _EnvironmentDataValues;
            }
        }
        private ObjectSet<EnvironmentDataValue> _EnvironmentDataValues;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Session> Sessions
        {
            get
            {
                if ((_Sessions == null))
                {
                    _Sessions = base.CreateObjectSet<Session>("Sessions");
                }
                return _Sessions;
            }
        }
        private ObjectSet<Session> _Sessions;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EnvironmentDataNames EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEnvironmentDataNames(EnvironmentDataName environmentDataName)
        {
            base.AddObject("EnvironmentDataNames", environmentDataName);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Features EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFeatures(Feature feature)
        {
            base.AddObject("Features", feature);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FeatureUses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFeatureUses(FeatureUse featureUse)
        {
            base.AddObject("FeatureUses", featureUse);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ExceptionGroups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToExceptionGroups(ExceptionGroup exceptionGroup)
        {
            base.AddObject("ExceptionGroups", exceptionGroup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Exceptions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToExceptions(Exception exception)
        {
            base.AddObject("Exceptions", exception);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ActivationMethods EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToActivationMethods(ActivationMethod activationMethod)
        {
            base.AddObject("ActivationMethods", activationMethod);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EnvironmentDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEnvironmentDatas(EnvironmentData environmentData)
        {
            base.AddObject("EnvironmentDatas", environmentData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EnvironmentDataValues EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEnvironmentDataValues(EnvironmentDataValue environmentDataValue)
        {
            base.AddObject("EnvironmentDataValues", environmentDataValue);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sessions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSessions(Session session)
        {
            base.AddObject("Sessions", session);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CollectorModel", Name="ActivationMethod")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ActivationMethod : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ActivationMethod object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static ActivationMethod CreateActivationMethod(global::System.Int32 id)
        {
            ActivationMethod activationMethod = new ActivationMethod();
            activationMethod.Id = id;
            return activationMethod;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CollectorModel", Name="EnvironmentData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EnvironmentData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EnvironmentData object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="sessionId">Initial value of the SessionId property.</param>
        /// <param name="environmentDataNameId">Initial value of the EnvironmentDataNameId property.</param>
        /// <param name="environmentDataValueId">Initial value of the EnvironmentDataValueId property.</param>
        public static EnvironmentData CreateEnvironmentData(global::System.Int32 id, global::System.Int32 sessionId, global::System.Int32 environmentDataNameId, global::System.Int32 environmentDataValueId)
        {
            EnvironmentData environmentData = new EnvironmentData();
            environmentData.Id = id;
            environmentData.SessionId = sessionId;
            environmentData.EnvironmentDataNameId = environmentDataNameId;
            environmentData.EnvironmentDataValueId = environmentDataValueId;
            return environmentData;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SessionId
        {
            get
            {
                return _SessionId;
            }
            set
            {
                OnSessionIdChanging(value);
                ReportPropertyChanging("SessionId");
                _SessionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SessionId");
                OnSessionIdChanged();
            }
        }
        private global::System.Int32 _SessionId;
        partial void OnSessionIdChanging(global::System.Int32 value);
        partial void OnSessionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EnvironmentDataNameId
        {
            get
            {
                return _EnvironmentDataNameId;
            }
            set
            {
                OnEnvironmentDataNameIdChanging(value);
                ReportPropertyChanging("EnvironmentDataNameId");
                _EnvironmentDataNameId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EnvironmentDataNameId");
                OnEnvironmentDataNameIdChanged();
            }
        }
        private global::System.Int32 _EnvironmentDataNameId;
        partial void OnEnvironmentDataNameIdChanging(global::System.Int32 value);
        partial void OnEnvironmentDataNameIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EnvironmentDataValueId
        {
            get
            {
                return _EnvironmentDataValueId;
            }
            set
            {
                OnEnvironmentDataValueIdChanging(value);
                ReportPropertyChanging("EnvironmentDataValueId");
                _EnvironmentDataValueId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EnvironmentDataValueId");
                OnEnvironmentDataValueIdChanged();
            }
        }
        private global::System.Int32 _EnvironmentDataValueId;
        partial void OnEnvironmentDataValueIdChanging(global::System.Int32 value);
        partial void OnEnvironmentDataValueIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CollectorModel", Name="EnvironmentDataName")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EnvironmentDataName : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EnvironmentDataName object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static EnvironmentDataName CreateEnvironmentDataName(global::System.Int32 id, global::System.String name)
        {
            EnvironmentDataName environmentDataName = new EnvironmentDataName();
            environmentDataName.Id = id;
            environmentDataName.Name = name;
            return environmentDataName;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CollectorModel", Name="EnvironmentDataValue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EnvironmentDataValue : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EnvironmentDataValue object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static EnvironmentDataValue CreateEnvironmentDataValue(global::System.Int32 id)
        {
            EnvironmentDataValue environmentDataValue = new EnvironmentDataValue();
            environmentDataValue.Id = id;
            return environmentDataValue;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CollectorModel", Name="Exception")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Exception : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Exception object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="sessionId">Initial value of the SessionId property.</param>
        /// <param name="exceptionGroupId">Initial value of the ExceptionGroupId property.</param>
        /// <param name="thrownAt">Initial value of the ThrownAt property.</param>
        /// <param name="stacktrace">Initial value of the Stacktrace property.</param>
        /// <param name="isFirstInSession">Initial value of the IsFirstInSession property.</param>
        public static Exception CreateException(global::System.Int32 id, global::System.Int32 sessionId, global::System.Int32 exceptionGroupId, global::System.DateTime thrownAt, global::System.String stacktrace, global::System.Boolean isFirstInSession)
        {
            Exception exception = new Exception();
            exception.Id = id;
            exception.SessionId = sessionId;
            exception.ExceptionGroupId = exceptionGroupId;
            exception.ThrownAt = thrownAt;
            exception.Stacktrace = stacktrace;
            exception.IsFirstInSession = isFirstInSession;
            return exception;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SessionId
        {
            get
            {
                return _SessionId;
            }
            set
            {
                OnSessionIdChanging(value);
                ReportPropertyChanging("SessionId");
                _SessionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SessionId");
                OnSessionIdChanged();
            }
        }
        private global::System.Int32 _SessionId;
        partial void OnSessionIdChanging(global::System.Int32 value);
        partial void OnSessionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExceptionGroupId
        {
            get
            {
                return _ExceptionGroupId;
            }
            set
            {
                OnExceptionGroupIdChanging(value);
                ReportPropertyChanging("ExceptionGroupId");
                _ExceptionGroupId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExceptionGroupId");
                OnExceptionGroupIdChanged();
            }
        }
        private global::System.Int32 _ExceptionGroupId;
        partial void OnExceptionGroupIdChanging(global::System.Int32 value);
        partial void OnExceptionGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ThrownAt
        {
            get
            {
                return _ThrownAt;
            }
            set
            {
                OnThrownAtChanging(value);
                ReportPropertyChanging("ThrownAt");
                _ThrownAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ThrownAt");
                OnThrownAtChanged();
            }
        }
        private global::System.DateTime _ThrownAt;
        partial void OnThrownAtChanging(global::System.DateTime value);
        partial void OnThrownAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Stacktrace
        {
            get
            {
                return _Stacktrace;
            }
            set
            {
                OnStacktraceChanging(value);
                ReportPropertyChanging("Stacktrace");
                _Stacktrace = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Stacktrace");
                OnStacktraceChanged();
            }
        }
        private global::System.String _Stacktrace;
        partial void OnStacktraceChanging(global::System.String value);
        partial void OnStacktraceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsFirstInSession
        {
            get
            {
                return _IsFirstInSession;
            }
            set
            {
                OnIsFirstInSessionChanging(value);
                ReportPropertyChanging("IsFirstInSession");
                _IsFirstInSession = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsFirstInSession");
                OnIsFirstInSessionChanged();
            }
        }
        private global::System.Boolean _IsFirstInSession;
        partial void OnIsFirstInSessionChanging(global::System.Boolean value);
        partial void OnIsFirstInSessionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CollectorModel", Name="ExceptionGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ExceptionGroup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ExceptionGroup object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="typeFingerprintSha256Hash">Initial value of the TypeFingerprintSha256Hash property.</param>
        /// <param name="exceptionType">Initial value of the ExceptionType property.</param>
        /// <param name="exceptionFingerprint">Initial value of the ExceptionFingerprint property.</param>
        /// <param name="exceptionLocation">Initial value of the ExceptionLocation property.</param>
        public static ExceptionGroup CreateExceptionGroup(global::System.Int32 id, global::System.String typeFingerprintSha256Hash, global::System.String exceptionType, global::System.String exceptionFingerprint, global::System.String exceptionLocation)
        {
            ExceptionGroup exceptionGroup = new ExceptionGroup();
            exceptionGroup.Id = id;
            exceptionGroup.TypeFingerprintSha256Hash = typeFingerprintSha256Hash;
            exceptionGroup.ExceptionType = exceptionType;
            exceptionGroup.ExceptionFingerprint = exceptionFingerprint;
            exceptionGroup.ExceptionLocation = exceptionLocation;
            return exceptionGroup;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TypeFingerprintSha256Hash
        {
            get
            {
                return _TypeFingerprintSha256Hash;
            }
            set
            {
                OnTypeFingerprintSha256HashChanging(value);
                ReportPropertyChanging("TypeFingerprintSha256Hash");
                _TypeFingerprintSha256Hash = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TypeFingerprintSha256Hash");
                OnTypeFingerprintSha256HashChanged();
            }
        }
        private global::System.String _TypeFingerprintSha256Hash;
        partial void OnTypeFingerprintSha256HashChanging(global::System.String value);
        partial void OnTypeFingerprintSha256HashChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ExceptionType
        {
            get
            {
                return _ExceptionType;
            }
            set
            {
                OnExceptionTypeChanging(value);
                ReportPropertyChanging("ExceptionType");
                _ExceptionType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ExceptionType");
                OnExceptionTypeChanged();
            }
        }
        private global::System.String _ExceptionType;
        partial void OnExceptionTypeChanging(global::System.String value);
        partial void OnExceptionTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ExceptionFingerprint
        {
            get
            {
                return _ExceptionFingerprint;
            }
            set
            {
                OnExceptionFingerprintChanging(value);
                ReportPropertyChanging("ExceptionFingerprint");
                _ExceptionFingerprint = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ExceptionFingerprint");
                OnExceptionFingerprintChanged();
            }
        }
        private global::System.String _ExceptionFingerprint;
        partial void OnExceptionFingerprintChanging(global::System.String value);
        partial void OnExceptionFingerprintChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ExceptionLocation
        {
            get
            {
                return _ExceptionLocation;
            }
            set
            {
                OnExceptionLocationChanging(value);
                ReportPropertyChanging("ExceptionLocation");
                _ExceptionLocation = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ExceptionLocation");
                OnExceptionLocationChanged();
            }
        }
        private global::System.String _ExceptionLocation;
        partial void OnExceptionLocationChanging(global::System.String value);
        partial void OnExceptionLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserComment
        {
            get
            {
                return _UserComment;
            }
            set
            {
                OnUserCommentChanging(value);
                ReportPropertyChanging("UserComment");
                _UserComment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserComment");
                OnUserCommentChanged();
            }
        }
        private global::System.String _UserComment;
        partial void OnUserCommentChanging(global::System.String value);
        partial void OnUserCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserFixedInRevision
        {
            get
            {
                return _UserFixedInRevision;
            }
            set
            {
                OnUserFixedInRevisionChanging(value);
                ReportPropertyChanging("UserFixedInRevision");
                _UserFixedInRevision = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserFixedInRevision");
                OnUserFixedInRevisionChanged();
            }
        }
        private Nullable<global::System.Int32> _UserFixedInRevision;
        partial void OnUserFixedInRevisionChanging(Nullable<global::System.Int32> value);
        partial void OnUserFixedInRevisionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CollectorModel", Name="Feature")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Feature : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Feature object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Feature CreateFeature(global::System.Int32 id, global::System.String name)
        {
            Feature feature = new Feature();
            feature.Id = id;
            feature.Name = name;
            return feature;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CollectorModel", Name="FeatureUse")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FeatureUse : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FeatureUse object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="sessionId">Initial value of the SessionId property.</param>
        /// <param name="useTime">Initial value of the UseTime property.</param>
        /// <param name="featureId">Initial value of the FeatureId property.</param>
        /// <param name="activationMethodId">Initial value of the ActivationMethodId property.</param>
        public static FeatureUse CreateFeatureUse(global::System.Int32 id, global::System.Int32 sessionId, global::System.DateTime useTime, global::System.Int32 featureId, global::System.Int32 activationMethodId)
        {
            FeatureUse featureUse = new FeatureUse();
            featureUse.Id = id;
            featureUse.SessionId = sessionId;
            featureUse.UseTime = useTime;
            featureUse.FeatureId = featureId;
            featureUse.ActivationMethodId = activationMethodId;
            return featureUse;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SessionId
        {
            get
            {
                return _SessionId;
            }
            set
            {
                OnSessionIdChanging(value);
                ReportPropertyChanging("SessionId");
                _SessionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SessionId");
                OnSessionIdChanged();
            }
        }
        private global::System.Int32 _SessionId;
        partial void OnSessionIdChanging(global::System.Int32 value);
        partial void OnSessionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UseTime
        {
            get
            {
                return _UseTime;
            }
            set
            {
                OnUseTimeChanging(value);
                ReportPropertyChanging("UseTime");
                _UseTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UseTime");
                OnUseTimeChanged();
            }
        }
        private global::System.DateTime _UseTime;
        partial void OnUseTimeChanging(global::System.DateTime value);
        partial void OnUseTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndTime;
        partial void OnEndTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FeatureId
        {
            get
            {
                return _FeatureId;
            }
            set
            {
                OnFeatureIdChanging(value);
                ReportPropertyChanging("FeatureId");
                _FeatureId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FeatureId");
                OnFeatureIdChanged();
            }
        }
        private global::System.Int32 _FeatureId;
        partial void OnFeatureIdChanging(global::System.Int32 value);
        partial void OnFeatureIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActivationMethodId
        {
            get
            {
                return _ActivationMethodId;
            }
            set
            {
                OnActivationMethodIdChanging(value);
                ReportPropertyChanging("ActivationMethodId");
                _ActivationMethodId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActivationMethodId");
                OnActivationMethodIdChanged();
            }
        }
        private global::System.Int32 _ActivationMethodId;
        partial void OnActivationMethodIdChanging(global::System.Int32 value);
        partial void OnActivationMethodIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CollectorModel", Name="Session")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Session : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Session object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="clientSessionId">Initial value of the ClientSessionId property.</param>
        /// <param name="startTime">Initial value of the StartTime property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        public static Session CreateSession(global::System.Int32 id, global::System.Int64 clientSessionId, global::System.DateTime startTime, global::System.Int32 userId)
        {
            Session session = new Session();
            session.Id = id;
            session.ClientSessionId = clientSessionId;
            session.StartTime = startTime;
            session.UserId = userId;
            return session;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ClientSessionId
        {
            get
            {
                return _ClientSessionId;
            }
            set
            {
                OnClientSessionIdChanging(value);
                ReportPropertyChanging("ClientSessionId");
                _ClientSessionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientSessionId");
                OnClientSessionIdChanged();
            }
        }
        private global::System.Int64 _ClientSessionId;
        partial void OnClientSessionIdChanging(global::System.Int64 value);
        partial void OnClientSessionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private global::System.DateTime _StartTime;
        partial void OnStartTimeChanging(global::System.DateTime value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndTime;
        partial void OnEndTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AppVersionMajor
        {
            get
            {
                return _AppVersionMajor;
            }
            set
            {
                OnAppVersionMajorChanging(value);
                ReportPropertyChanging("AppVersionMajor");
                _AppVersionMajor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppVersionMajor");
                OnAppVersionMajorChanged();
            }
        }
        private Nullable<global::System.Int32> _AppVersionMajor;
        partial void OnAppVersionMajorChanging(Nullable<global::System.Int32> value);
        partial void OnAppVersionMajorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AppVersionMinor
        {
            get
            {
                return _AppVersionMinor;
            }
            set
            {
                OnAppVersionMinorChanging(value);
                ReportPropertyChanging("AppVersionMinor");
                _AppVersionMinor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppVersionMinor");
                OnAppVersionMinorChanged();
            }
        }
        private Nullable<global::System.Int32> _AppVersionMinor;
        partial void OnAppVersionMinorChanging(Nullable<global::System.Int32> value);
        partial void OnAppVersionMinorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AppVersionBuild
        {
            get
            {
                return _AppVersionBuild;
            }
            set
            {
                OnAppVersionBuildChanging(value);
                ReportPropertyChanging("AppVersionBuild");
                _AppVersionBuild = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppVersionBuild");
                OnAppVersionBuildChanged();
            }
        }
        private Nullable<global::System.Int32> _AppVersionBuild;
        partial void OnAppVersionBuildChanging(Nullable<global::System.Int32> value);
        partial void OnAppVersionBuildChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AppVersionRevision
        {
            get
            {
                return _AppVersionRevision;
            }
            set
            {
                OnAppVersionRevisionChanging(value);
                ReportPropertyChanging("AppVersionRevision");
                _AppVersionRevision = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppVersionRevision");
                OnAppVersionRevisionChanged();
            }
        }
        private Nullable<global::System.Int32> _AppVersionRevision;
        partial void OnAppVersionRevisionChanging(Nullable<global::System.Int32> value);
        partial void OnAppVersionRevisionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CollectorModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="associatedGuid">Initial value of the AssociatedGuid property.</param>
        public static User CreateUser(global::System.Int32 id, global::System.String associatedGuid)
        {
            User user = new User();
            user.Id = id;
            user.AssociatedGuid = associatedGuid;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AssociatedGuid
        {
            get
            {
                return _AssociatedGuid;
            }
            set
            {
                OnAssociatedGuidChanging(value);
                ReportPropertyChanging("AssociatedGuid");
                _AssociatedGuid = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AssociatedGuid");
                OnAssociatedGuidChanged();
            }
        }
        private global::System.String _AssociatedGuid;
        partial void OnAssociatedGuidChanging(global::System.String value);
        partial void OnAssociatedGuidChanged();

        #endregion
    
    }

    #endregion
    
}
