//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ICSharpCode.UsageDataCollector.DataAccess.Collector
{
    #region Kontexte
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    public partial class UDCContext : ObjectContext
    {
        #region Konstruktoren
    
        /// <summary>
        /// Initialisiert ein neues UDCContext-Objekt mithilfe der in Abschnitt 'UDCContext' der Anwendungskonfigurationsdatei gefundenen Verbindungszeichenfolge.
        /// </summary>
        public UDCContext() : base("name=UDCContext", "UDCContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisiert ein neues UDCContext-Objekt.
        /// </summary>
        public UDCContext(string connectionString) : base(connectionString, "UDCContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisiert ein neues UDCContext-Objekt.
        /// </summary>
        public UDCContext(EntityConnection connection) : base(connection, "UDCContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partielle Methoden
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet-Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<EnvironmentDataName> EnvironmentDataNames
        {
            get
            {
                if ((_EnvironmentDataNames == null))
                {
                    _EnvironmentDataNames = base.CreateObjectSet<EnvironmentDataName>("EnvironmentDataNames");
                }
                return _EnvironmentDataNames;
            }
        }
        private ObjectSet<EnvironmentDataName> _EnvironmentDataNames;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Feature> Features
        {
            get
            {
                if ((_Features == null))
                {
                    _Features = base.CreateObjectSet<Feature>("Features");
                }
                return _Features;
            }
        }
        private ObjectSet<Feature> _Features;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<FeatureUse> FeatureUses
        {
            get
            {
                if ((_FeatureUses == null))
                {
                    _FeatureUses = base.CreateObjectSet<FeatureUse>("FeatureUses");
                }
                return _FeatureUses;
            }
        }
        private ObjectSet<FeatureUse> _FeatureUses;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<ExceptionGroup> ExceptionGroups
        {
            get
            {
                if ((_ExceptionGroups == null))
                {
                    _ExceptionGroups = base.CreateObjectSet<ExceptionGroup>("ExceptionGroups");
                }
                return _ExceptionGroups;
            }
        }
        private ObjectSet<ExceptionGroup> _ExceptionGroups;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Exception> Exceptions
        {
            get
            {
                if ((_Exceptions == null))
                {
                    _Exceptions = base.CreateObjectSet<Exception>("Exceptions");
                }
                return _Exceptions;
            }
        }
        private ObjectSet<Exception> _Exceptions;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<ActivationMethod> ActivationMethods
        {
            get
            {
                if ((_ActivationMethods == null))
                {
                    _ActivationMethods = base.CreateObjectSet<ActivationMethod>("ActivationMethods");
                }
                return _ActivationMethods;
            }
        }
        private ObjectSet<ActivationMethod> _ActivationMethods;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<EnvironmentData> EnvironmentDatas
        {
            get
            {
                if ((_EnvironmentDatas == null))
                {
                    _EnvironmentDatas = base.CreateObjectSet<EnvironmentData>("EnvironmentDatas");
                }
                return _EnvironmentDatas;
            }
        }
        private ObjectSet<EnvironmentData> _EnvironmentDatas;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<EnvironmentDataValue> EnvironmentDataValues
        {
            get
            {
                if ((_EnvironmentDataValues == null))
                {
                    _EnvironmentDataValues = base.CreateObjectSet<EnvironmentDataValue>("EnvironmentDataValues");
                }
                return _EnvironmentDataValues;
            }
        }
        private ObjectSet<EnvironmentDataValue> _EnvironmentDataValues;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Session> Sessions
        {
            get
            {
                if ((_Sessions == null))
                {
                    _Sessions = base.CreateObjectSet<Session>("Sessions");
                }
                return _Sessions;
            }
        }
        private ObjectSet<Session> _Sessions;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Commit> Commits
        {
            get
            {
                if ((_Commits == null))
                {
                    _Commits = base.CreateObjectSet<Commit>("Commits");
                }
                return _Commits;
            }
        }
        private ObjectSet<Commit> _Commits;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<TaggedCommit> TaggedCommits
        {
            get
            {
                if ((_TaggedCommits == null))
                {
                    _TaggedCommits = base.CreateObjectSet<TaggedCommit>("TaggedCommits");
                }
                return _TaggedCommits;
            }
        }
        private ObjectSet<TaggedCommit> _TaggedCommits;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<CommitRelation> CommitRelations
        {
            get
            {
                if ((_CommitRelations == null))
                {
                    _CommitRelations = base.CreateObjectSet<CommitRelation>("CommitRelations");
                }
                return _CommitRelations;
            }
        }
        private ObjectSet<CommitRelation> _CommitRelations;

        #endregion
        #region AddTo-Methoden
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'EnvironmentDataNames'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToEnvironmentDataNames(EnvironmentDataName environmentDataName)
        {
            base.AddObject("EnvironmentDataNames", environmentDataName);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Features'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToFeatures(Feature feature)
        {
            base.AddObject("Features", feature);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'FeatureUses'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToFeatureUses(FeatureUse featureUse)
        {
            base.AddObject("FeatureUses", featureUse);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Users'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'ExceptionGroups'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToExceptionGroups(ExceptionGroup exceptionGroup)
        {
            base.AddObject("ExceptionGroups", exceptionGroup);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Exceptions'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToExceptions(Exception exception)
        {
            base.AddObject("Exceptions", exception);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'ActivationMethods'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToActivationMethods(ActivationMethod activationMethod)
        {
            base.AddObject("ActivationMethods", activationMethod);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'EnvironmentDatas'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToEnvironmentDatas(EnvironmentData environmentData)
        {
            base.AddObject("EnvironmentDatas", environmentData);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'EnvironmentDataValues'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToEnvironmentDataValues(EnvironmentDataValue environmentDataValue)
        {
            base.AddObject("EnvironmentDataValues", environmentDataValue);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Sessions'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToSessions(Session session)
        {
            base.AddObject("Sessions", session);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Commits'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToCommits(Commit commit)
        {
            base.AddObject("Commits", commit);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'TaggedCommits'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToTaggedCommits(TaggedCommit taggedCommit)
        {
            base.AddObject("TaggedCommits", taggedCommit);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'CommitRelations'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToCommitRelations(CommitRelation commitRelation)
        {
            base.AddObject("CommitRelations", commitRelation);
        }

        #endregion
    }
    

    #endregion
    
    #region Entitäten
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CollectorModel", Name="ActivationMethod")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ActivationMethod : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues ActivationMethod-Objekt.
        /// </summary>
        /// <param name="id">Anfangswert der Eigenschaft Id.</param>
        public static ActivationMethod CreateActivationMethod(global::System.Int32 id)
        {
            ActivationMethod activationMethod = new ActivationMethod();
            activationMethod.Id = id;
            return activationMethod;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CollectorModel", Name="Commit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Commit : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Commit-Objekt.
        /// </summary>
        /// <param name="id">Anfangswert der Eigenschaft Id.</param>
        /// <param name="hash">Anfangswert der Eigenschaft Hash.</param>
        /// <param name="commitDate">Anfangswert der Eigenschaft CommitDate.</param>
        public static Commit CreateCommit(global::System.Int32 id, global::System.String hash, global::System.DateTime commitDate)
        {
            Commit commit = new Commit();
            commit.Id = id;
            commit.Hash = hash;
            commit.CommitDate = commitDate;
            return commit;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Hash
        {
            get
            {
                return _Hash;
            }
            set
            {
                OnHashChanging(value);
                ReportPropertyChanging("Hash");
                _Hash = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Hash");
                OnHashChanged();
            }
        }
        private global::System.String _Hash;
        partial void OnHashChanging(global::System.String value);
        partial void OnHashChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CommitDate
        {
            get
            {
                return _CommitDate;
            }
            set
            {
                OnCommitDateChanging(value);
                ReportPropertyChanging("CommitDate");
                _CommitDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CommitDate");
                OnCommitDateChanged();
            }
        }
        private global::System.DateTime _CommitDate;
        partial void OnCommitDateChanging(global::System.DateTime value);
        partial void OnCommitDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CollectorModel", Name="CommitRelation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CommitRelation : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues CommitRelation-Objekt.
        /// </summary>
        /// <param name="parentCommit">Anfangswert der Eigenschaft ParentCommit.</param>
        /// <param name="childCommit">Anfangswert der Eigenschaft ChildCommit.</param>
        public static CommitRelation CreateCommitRelation(global::System.Int32 parentCommit, global::System.Int32 childCommit)
        {
            CommitRelation commitRelation = new CommitRelation();
            commitRelation.ParentCommit = parentCommit;
            commitRelation.ChildCommit = childCommit;
            return commitRelation;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ParentCommit
        {
            get
            {
                return _ParentCommit;
            }
            set
            {
                if (_ParentCommit != value)
                {
                    OnParentCommitChanging(value);
                    ReportPropertyChanging("ParentCommit");
                    _ParentCommit = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ParentCommit");
                    OnParentCommitChanged();
                }
            }
        }
        private global::System.Int32 _ParentCommit;
        partial void OnParentCommitChanging(global::System.Int32 value);
        partial void OnParentCommitChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ChildCommit
        {
            get
            {
                return _ChildCommit;
            }
            set
            {
                if (_ChildCommit != value)
                {
                    OnChildCommitChanging(value);
                    ReportPropertyChanging("ChildCommit");
                    _ChildCommit = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ChildCommit");
                    OnChildCommitChanged();
                }
            }
        }
        private global::System.Int32 _ChildCommit;
        partial void OnChildCommitChanging(global::System.Int32 value);
        partial void OnChildCommitChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CollectorModel", Name="EnvironmentData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EnvironmentData : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues EnvironmentData-Objekt.
        /// </summary>
        /// <param name="id">Anfangswert der Eigenschaft Id.</param>
        /// <param name="sessionId">Anfangswert der Eigenschaft SessionId.</param>
        /// <param name="environmentDataNameId">Anfangswert der Eigenschaft EnvironmentDataNameId.</param>
        /// <param name="environmentDataValueId">Anfangswert der Eigenschaft EnvironmentDataValueId.</param>
        public static EnvironmentData CreateEnvironmentData(global::System.Int32 id, global::System.Int32 sessionId, global::System.Int32 environmentDataNameId, global::System.Int32 environmentDataValueId)
        {
            EnvironmentData environmentData = new EnvironmentData();
            environmentData.Id = id;
            environmentData.SessionId = sessionId;
            environmentData.EnvironmentDataNameId = environmentDataNameId;
            environmentData.EnvironmentDataValueId = environmentDataValueId;
            return environmentData;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SessionId
        {
            get
            {
                return _SessionId;
            }
            set
            {
                OnSessionIdChanging(value);
                ReportPropertyChanging("SessionId");
                _SessionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SessionId");
                OnSessionIdChanged();
            }
        }
        private global::System.Int32 _SessionId;
        partial void OnSessionIdChanging(global::System.Int32 value);
        partial void OnSessionIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EnvironmentDataNameId
        {
            get
            {
                return _EnvironmentDataNameId;
            }
            set
            {
                OnEnvironmentDataNameIdChanging(value);
                ReportPropertyChanging("EnvironmentDataNameId");
                _EnvironmentDataNameId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EnvironmentDataNameId");
                OnEnvironmentDataNameIdChanged();
            }
        }
        private global::System.Int32 _EnvironmentDataNameId;
        partial void OnEnvironmentDataNameIdChanging(global::System.Int32 value);
        partial void OnEnvironmentDataNameIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EnvironmentDataValueId
        {
            get
            {
                return _EnvironmentDataValueId;
            }
            set
            {
                OnEnvironmentDataValueIdChanging(value);
                ReportPropertyChanging("EnvironmentDataValueId");
                _EnvironmentDataValueId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EnvironmentDataValueId");
                OnEnvironmentDataValueIdChanged();
            }
        }
        private global::System.Int32 _EnvironmentDataValueId;
        partial void OnEnvironmentDataValueIdChanging(global::System.Int32 value);
        partial void OnEnvironmentDataValueIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CollectorModel", Name="EnvironmentDataName")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EnvironmentDataName : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues EnvironmentDataName-Objekt.
        /// </summary>
        /// <param name="id">Anfangswert der Eigenschaft Id.</param>
        /// <param name="name">Anfangswert der Eigenschaft Name.</param>
        public static EnvironmentDataName CreateEnvironmentDataName(global::System.Int32 id, global::System.String name)
        {
            EnvironmentDataName environmentDataName = new EnvironmentDataName();
            environmentDataName.Id = id;
            environmentDataName.Name = name;
            return environmentDataName;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CollectorModel", Name="EnvironmentDataValue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EnvironmentDataValue : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues EnvironmentDataValue-Objekt.
        /// </summary>
        /// <param name="id">Anfangswert der Eigenschaft Id.</param>
        public static EnvironmentDataValue CreateEnvironmentDataValue(global::System.Int32 id)
        {
            EnvironmentDataValue environmentDataValue = new EnvironmentDataValue();
            environmentDataValue.Id = id;
            return environmentDataValue;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CollectorModel", Name="Exception")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Exception : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Exception-Objekt.
        /// </summary>
        /// <param name="id">Anfangswert der Eigenschaft Id.</param>
        /// <param name="sessionId">Anfangswert der Eigenschaft SessionId.</param>
        /// <param name="exceptionGroupId">Anfangswert der Eigenschaft ExceptionGroupId.</param>
        /// <param name="thrownAt">Anfangswert der Eigenschaft ThrownAt.</param>
        /// <param name="stacktrace">Anfangswert der Eigenschaft Stacktrace.</param>
        /// <param name="isFirstInSession">Anfangswert der Eigenschaft IsFirstInSession.</param>
        public static Exception CreateException(global::System.Int32 id, global::System.Int32 sessionId, global::System.Int32 exceptionGroupId, global::System.DateTime thrownAt, global::System.String stacktrace, global::System.Boolean isFirstInSession)
        {
            Exception exception = new Exception();
            exception.Id = id;
            exception.SessionId = sessionId;
            exception.ExceptionGroupId = exceptionGroupId;
            exception.ThrownAt = thrownAt;
            exception.Stacktrace = stacktrace;
            exception.IsFirstInSession = isFirstInSession;
            return exception;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SessionId
        {
            get
            {
                return _SessionId;
            }
            set
            {
                OnSessionIdChanging(value);
                ReportPropertyChanging("SessionId");
                _SessionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SessionId");
                OnSessionIdChanged();
            }
        }
        private global::System.Int32 _SessionId;
        partial void OnSessionIdChanging(global::System.Int32 value);
        partial void OnSessionIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExceptionGroupId
        {
            get
            {
                return _ExceptionGroupId;
            }
            set
            {
                OnExceptionGroupIdChanging(value);
                ReportPropertyChanging("ExceptionGroupId");
                _ExceptionGroupId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExceptionGroupId");
                OnExceptionGroupIdChanged();
            }
        }
        private global::System.Int32 _ExceptionGroupId;
        partial void OnExceptionGroupIdChanging(global::System.Int32 value);
        partial void OnExceptionGroupIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ThrownAt
        {
            get
            {
                return _ThrownAt;
            }
            set
            {
                OnThrownAtChanging(value);
                ReportPropertyChanging("ThrownAt");
                _ThrownAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ThrownAt");
                OnThrownAtChanged();
            }
        }
        private global::System.DateTime _ThrownAt;
        partial void OnThrownAtChanging(global::System.DateTime value);
        partial void OnThrownAtChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Stacktrace
        {
            get
            {
                return _Stacktrace;
            }
            set
            {
                OnStacktraceChanging(value);
                ReportPropertyChanging("Stacktrace");
                _Stacktrace = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Stacktrace");
                OnStacktraceChanged();
            }
        }
        private global::System.String _Stacktrace;
        partial void OnStacktraceChanging(global::System.String value);
        partial void OnStacktraceChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsFirstInSession
        {
            get
            {
                return _IsFirstInSession;
            }
            set
            {
                OnIsFirstInSessionChanging(value);
                ReportPropertyChanging("IsFirstInSession");
                _IsFirstInSession = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsFirstInSession");
                OnIsFirstInSessionChanged();
            }
        }
        private global::System.Boolean _IsFirstInSession;
        partial void OnIsFirstInSessionChanging(global::System.Boolean value);
        partial void OnIsFirstInSessionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CollectorModel", Name="ExceptionGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ExceptionGroup : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues ExceptionGroup-Objekt.
        /// </summary>
        /// <param name="id">Anfangswert der Eigenschaft Id.</param>
        /// <param name="typeFingerprintSha256Hash">Anfangswert der Eigenschaft TypeFingerprintSha256Hash.</param>
        /// <param name="exceptionType">Anfangswert der Eigenschaft ExceptionType.</param>
        /// <param name="exceptionFingerprint">Anfangswert der Eigenschaft ExceptionFingerprint.</param>
        /// <param name="exceptionLocation">Anfangswert der Eigenschaft ExceptionLocation.</param>
        public static ExceptionGroup CreateExceptionGroup(global::System.Int32 id, global::System.String typeFingerprintSha256Hash, global::System.String exceptionType, global::System.String exceptionFingerprint, global::System.String exceptionLocation)
        {
            ExceptionGroup exceptionGroup = new ExceptionGroup();
            exceptionGroup.Id = id;
            exceptionGroup.TypeFingerprintSha256Hash = typeFingerprintSha256Hash;
            exceptionGroup.ExceptionType = exceptionType;
            exceptionGroup.ExceptionFingerprint = exceptionFingerprint;
            exceptionGroup.ExceptionLocation = exceptionLocation;
            return exceptionGroup;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TypeFingerprintSha256Hash
        {
            get
            {
                return _TypeFingerprintSha256Hash;
            }
            set
            {
                OnTypeFingerprintSha256HashChanging(value);
                ReportPropertyChanging("TypeFingerprintSha256Hash");
                _TypeFingerprintSha256Hash = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TypeFingerprintSha256Hash");
                OnTypeFingerprintSha256HashChanged();
            }
        }
        private global::System.String _TypeFingerprintSha256Hash;
        partial void OnTypeFingerprintSha256HashChanging(global::System.String value);
        partial void OnTypeFingerprintSha256HashChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ExceptionType
        {
            get
            {
                return _ExceptionType;
            }
            set
            {
                OnExceptionTypeChanging(value);
                ReportPropertyChanging("ExceptionType");
                _ExceptionType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ExceptionType");
                OnExceptionTypeChanged();
            }
        }
        private global::System.String _ExceptionType;
        partial void OnExceptionTypeChanging(global::System.String value);
        partial void OnExceptionTypeChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ExceptionFingerprint
        {
            get
            {
                return _ExceptionFingerprint;
            }
            set
            {
                OnExceptionFingerprintChanging(value);
                ReportPropertyChanging("ExceptionFingerprint");
                _ExceptionFingerprint = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ExceptionFingerprint");
                OnExceptionFingerprintChanged();
            }
        }
        private global::System.String _ExceptionFingerprint;
        partial void OnExceptionFingerprintChanging(global::System.String value);
        partial void OnExceptionFingerprintChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ExceptionLocation
        {
            get
            {
                return _ExceptionLocation;
            }
            set
            {
                OnExceptionLocationChanging(value);
                ReportPropertyChanging("ExceptionLocation");
                _ExceptionLocation = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ExceptionLocation");
                OnExceptionLocationChanged();
            }
        }
        private global::System.String _ExceptionLocation;
        partial void OnExceptionLocationChanging(global::System.String value);
        partial void OnExceptionLocationChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserComment
        {
            get
            {
                return _UserComment;
            }
            set
            {
                OnUserCommentChanging(value);
                ReportPropertyChanging("UserComment");
                _UserComment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserComment");
                OnUserCommentChanged();
            }
        }
        private global::System.String _UserComment;
        partial void OnUserCommentChanging(global::System.String value);
        partial void OnUserCommentChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserFixedInCommit
        {
            get
            {
                return _UserFixedInCommit;
            }
            set
            {
                OnUserFixedInCommitChanging(value);
                ReportPropertyChanging("UserFixedInCommit");
                _UserFixedInCommit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserFixedInCommit");
                OnUserFixedInCommitChanged();
            }
        }
        private Nullable<global::System.Int32> _UserFixedInCommit;
        partial void OnUserFixedInCommitChanging(Nullable<global::System.Int32> value);
        partial void OnUserFixedInCommitChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CollectorModel", Name="Feature")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Feature : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Feature-Objekt.
        /// </summary>
        /// <param name="id">Anfangswert der Eigenschaft Id.</param>
        /// <param name="name">Anfangswert der Eigenschaft Name.</param>
        public static Feature CreateFeature(global::System.Int32 id, global::System.String name)
        {
            Feature feature = new Feature();
            feature.Id = id;
            feature.Name = name;
            return feature;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CollectorModel", Name="FeatureUse")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FeatureUse : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues FeatureUse-Objekt.
        /// </summary>
        /// <param name="id">Anfangswert der Eigenschaft Id.</param>
        /// <param name="sessionId">Anfangswert der Eigenschaft SessionId.</param>
        /// <param name="useTime">Anfangswert der Eigenschaft UseTime.</param>
        /// <param name="featureId">Anfangswert der Eigenschaft FeatureId.</param>
        /// <param name="activationMethodId">Anfangswert der Eigenschaft ActivationMethodId.</param>
        public static FeatureUse CreateFeatureUse(global::System.Int32 id, global::System.Int32 sessionId, global::System.DateTime useTime, global::System.Int32 featureId, global::System.Int32 activationMethodId)
        {
            FeatureUse featureUse = new FeatureUse();
            featureUse.Id = id;
            featureUse.SessionId = sessionId;
            featureUse.UseTime = useTime;
            featureUse.FeatureId = featureId;
            featureUse.ActivationMethodId = activationMethodId;
            return featureUse;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SessionId
        {
            get
            {
                return _SessionId;
            }
            set
            {
                OnSessionIdChanging(value);
                ReportPropertyChanging("SessionId");
                _SessionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SessionId");
                OnSessionIdChanged();
            }
        }
        private global::System.Int32 _SessionId;
        partial void OnSessionIdChanging(global::System.Int32 value);
        partial void OnSessionIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UseTime
        {
            get
            {
                return _UseTime;
            }
            set
            {
                OnUseTimeChanging(value);
                ReportPropertyChanging("UseTime");
                _UseTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UseTime");
                OnUseTimeChanged();
            }
        }
        private global::System.DateTime _UseTime;
        partial void OnUseTimeChanging(global::System.DateTime value);
        partial void OnUseTimeChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndTime;
        partial void OnEndTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEndTimeChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FeatureId
        {
            get
            {
                return _FeatureId;
            }
            set
            {
                OnFeatureIdChanging(value);
                ReportPropertyChanging("FeatureId");
                _FeatureId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FeatureId");
                OnFeatureIdChanged();
            }
        }
        private global::System.Int32 _FeatureId;
        partial void OnFeatureIdChanging(global::System.Int32 value);
        partial void OnFeatureIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActivationMethodId
        {
            get
            {
                return _ActivationMethodId;
            }
            set
            {
                OnActivationMethodIdChanging(value);
                ReportPropertyChanging("ActivationMethodId");
                _ActivationMethodId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActivationMethodId");
                OnActivationMethodIdChanged();
            }
        }
        private global::System.Int32 _ActivationMethodId;
        partial void OnActivationMethodIdChanging(global::System.Int32 value);
        partial void OnActivationMethodIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CollectorModel", Name="Session")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Session : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Session-Objekt.
        /// </summary>
        /// <param name="id">Anfangswert der Eigenschaft Id.</param>
        /// <param name="clientSessionId">Anfangswert der Eigenschaft ClientSessionId.</param>
        /// <param name="startTime">Anfangswert der Eigenschaft StartTime.</param>
        /// <param name="userId">Anfangswert der Eigenschaft UserId.</param>
        /// <param name="isDebug">Anfangswert der Eigenschaft IsDebug.</param>
        public static Session CreateSession(global::System.Int32 id, global::System.Int64 clientSessionId, global::System.DateTime startTime, global::System.Int32 userId, global::System.Boolean isDebug)
        {
            Session session = new Session();
            session.Id = id;
            session.ClientSessionId = clientSessionId;
            session.StartTime = startTime;
            session.UserId = userId;
            session.IsDebug = isDebug;
            return session;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ClientSessionId
        {
            get
            {
                return _ClientSessionId;
            }
            set
            {
                OnClientSessionIdChanging(value);
                ReportPropertyChanging("ClientSessionId");
                _ClientSessionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientSessionId");
                OnClientSessionIdChanged();
            }
        }
        private global::System.Int64 _ClientSessionId;
        partial void OnClientSessionIdChanging(global::System.Int64 value);
        partial void OnClientSessionIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private global::System.DateTime _StartTime;
        partial void OnStartTimeChanging(global::System.DateTime value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndTime;
        partial void OnEndTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEndTimeChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AppVersionMajor
        {
            get
            {
                return _AppVersionMajor;
            }
            set
            {
                OnAppVersionMajorChanging(value);
                ReportPropertyChanging("AppVersionMajor");
                _AppVersionMajor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppVersionMajor");
                OnAppVersionMajorChanged();
            }
        }
        private Nullable<global::System.Int32> _AppVersionMajor;
        partial void OnAppVersionMajorChanging(Nullable<global::System.Int32> value);
        partial void OnAppVersionMajorChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AppVersionMinor
        {
            get
            {
                return _AppVersionMinor;
            }
            set
            {
                OnAppVersionMinorChanging(value);
                ReportPropertyChanging("AppVersionMinor");
                _AppVersionMinor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppVersionMinor");
                OnAppVersionMinorChanged();
            }
        }
        private Nullable<global::System.Int32> _AppVersionMinor;
        partial void OnAppVersionMinorChanging(Nullable<global::System.Int32> value);
        partial void OnAppVersionMinorChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AppVersionBuild
        {
            get
            {
                return _AppVersionBuild;
            }
            set
            {
                OnAppVersionBuildChanging(value);
                ReportPropertyChanging("AppVersionBuild");
                _AppVersionBuild = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppVersionBuild");
                OnAppVersionBuildChanged();
            }
        }
        private Nullable<global::System.Int32> _AppVersionBuild;
        partial void OnAppVersionBuildChanging(Nullable<global::System.Int32> value);
        partial void OnAppVersionBuildChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AppVersionRevision
        {
            get
            {
                return _AppVersionRevision;
            }
            set
            {
                OnAppVersionRevisionChanging(value);
                ReportPropertyChanging("AppVersionRevision");
                _AppVersionRevision = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppVersionRevision");
                OnAppVersionRevisionChanged();
            }
        }
        private Nullable<global::System.Int32> _AppVersionRevision;
        partial void OnAppVersionRevisionChanging(Nullable<global::System.Int32> value);
        partial void OnAppVersionRevisionChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CommitId
        {
            get
            {
                return _CommitId;
            }
            set
            {
                OnCommitIdChanging(value);
                ReportPropertyChanging("CommitId");
                _CommitId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CommitId");
                OnCommitIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CommitId;
        partial void OnCommitIdChanging(Nullable<global::System.Int32> value);
        partial void OnCommitIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsDebug
        {
            get
            {
                return _IsDebug;
            }
            set
            {
                OnIsDebugChanging(value);
                ReportPropertyChanging("IsDebug");
                _IsDebug = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDebug");
                OnIsDebugChanged();
            }
        }
        private global::System.Boolean _IsDebug;
        partial void OnIsDebugChanging(global::System.Boolean value);
        partial void OnIsDebugChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FirstException
        {
            get
            {
                return _FirstException;
            }
            set
            {
                OnFirstExceptionChanging(value);
                ReportPropertyChanging("FirstException");
                _FirstException = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FirstException");
                OnFirstExceptionChanged();
            }
        }
        private Nullable<global::System.DateTime> _FirstException;
        partial void OnFirstExceptionChanging(Nullable<global::System.DateTime> value);
        partial void OnFirstExceptionChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastFeatureUse
        {
            get
            {
                return _LastFeatureUse;
            }
            set
            {
                OnLastFeatureUseChanging(value);
                ReportPropertyChanging("LastFeatureUse");
                _LastFeatureUse = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastFeatureUse");
                OnLastFeatureUseChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastFeatureUse;
        partial void OnLastFeatureUseChanging(Nullable<global::System.DateTime> value);
        partial void OnLastFeatureUseChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CollectorModel", Name="TaggedCommit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TaggedCommit : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues TaggedCommit-Objekt.
        /// </summary>
        /// <param name="tagId">Anfangswert der Eigenschaft TagId.</param>
        /// <param name="commitId">Anfangswert der Eigenschaft CommitId.</param>
        /// <param name="name">Anfangswert der Eigenschaft Name.</param>
        /// <param name="isRelease">Anfangswert der Eigenschaft IsRelease.</param>
        public static TaggedCommit CreateTaggedCommit(global::System.Int32 tagId, global::System.Int32 commitId, global::System.String name, global::System.Boolean isRelease)
        {
            TaggedCommit taggedCommit = new TaggedCommit();
            taggedCommit.TagId = tagId;
            taggedCommit.CommitId = commitId;
            taggedCommit.Name = name;
            taggedCommit.IsRelease = isRelease;
            return taggedCommit;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TagId
        {
            get
            {
                return _TagId;
            }
            set
            {
                if (_TagId != value)
                {
                    OnTagIdChanging(value);
                    ReportPropertyChanging("TagId");
                    _TagId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TagId");
                    OnTagIdChanged();
                }
            }
        }
        private global::System.Int32 _TagId;
        partial void OnTagIdChanging(global::System.Int32 value);
        partial void OnTagIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CommitId
        {
            get
            {
                return _CommitId;
            }
            set
            {
                OnCommitIdChanging(value);
                ReportPropertyChanging("CommitId");
                _CommitId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CommitId");
                OnCommitIdChanged();
            }
        }
        private global::System.Int32 _CommitId;
        partial void OnCommitIdChanging(global::System.Int32 value);
        partial void OnCommitIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsRelease
        {
            get
            {
                return _IsRelease;
            }
            set
            {
                OnIsReleaseChanging(value);
                ReportPropertyChanging("IsRelease");
                _IsRelease = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsRelease");
                OnIsReleaseChanged();
            }
        }
        private global::System.Boolean _IsRelease;
        partial void OnIsReleaseChanging(global::System.Boolean value);
        partial void OnIsReleaseChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CollectorModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues User-Objekt.
        /// </summary>
        /// <param name="id">Anfangswert der Eigenschaft Id.</param>
        /// <param name="associatedGuid">Anfangswert der Eigenschaft AssociatedGuid.</param>
        public static User CreateUser(global::System.Int32 id, global::System.String associatedGuid)
        {
            User user = new User();
            user.Id = id;
            user.AssociatedGuid = associatedGuid;
            return user;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AssociatedGuid
        {
            get
            {
                return _AssociatedGuid;
            }
            set
            {
                OnAssociatedGuidChanging(value);
                ReportPropertyChanging("AssociatedGuid");
                _AssociatedGuid = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AssociatedGuid");
                OnAssociatedGuidChanged();
            }
        }
        private global::System.String _AssociatedGuid;
        partial void OnAssociatedGuidChanging(global::System.String value);
        partial void OnAssociatedGuidChanged();

        #endregion
    
    }

    #endregion
    
}
